for ([a,b] in c);
for ([a,b] of c);
for ([a,b];;);
for (var [a,b] in c);
for (var [a,b] of c);
for (var [a,b] = c;;);
for (let [a,b] in c);
for (let [a,b] of c);
for (let [a,b] = c;;);
for (const [a,b] in c);
for (const [a,b] of c);
for (const [a,b] = c;;);