name: "Run unit tests"

on:
  - push
  - pull_request

env:
  COMPOSER_MEMORY_LIMIT: -1

jobs:
  test:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 12
      matrix:
        php: ['5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json,mbstring

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run unit tests
        run: ./vendor/bin/phpunit -c phpunit.xml
